
### liked Mountain(Success)



POST http://localhost:8080/likes/me/mountains
Authorization: Bearer test
Content-Type: application/json

{
    "mountainNo" : 2
}



### Get ComminityComments(Success)
GET http://localhost:8080/communities/53/comments
Authorization: Bearer test
Content-Type: application/json





### Delete ComminityComments(Success)
DELETE http://localhost:8080/likes/me/mountains/1
Authorization: Bearer test2
Content-Type: application/json



